### ISSUE TITLE
Latest hugo has a different organization

### ISSUE THREAD

**Issue by orsenthil** [spencerlyon2/hugo_gh_blog#2]
I could not follow this blog instructions with latest hugo. At the least, config.yaml is changed to config.toml and then it gave an error on .BaseUrl with themes need to point to .BaseURL.

Is this specific to certain version of hugo.

**Comment by hammyau** [comment]
Change the .Site.BaseUrl to .SiteBaseURL in both the index.html file and the chrome/header.html file

**Comment by kotse** [comment]
Just a comment on the last post - you still need the dot between Site and BaseURL or it will still fail with the same error.

so you need to uppercase Url into URL, i.e.  `.Site.BaseUrl` to `.Site.BaseURL`
