### ISSUE TITLE
static folder - css files?

### ISSUE THREAD

**Issue by dazinator** [spencerlyon2/hugo_gh_blog#4]
Hello,

I am following your blog here: https://gohugo.io/tutorials/github-pages-blog/
I have got to here:

> The next step is to define the look and feel of your new website. Because Hugo will generate the site using HTML templates written by the user (you), this step is very subjective. I will merely present one possible theme that could be used to generate a blog. I decided to base the example project on a Jekyll theme called Lanyon. The Lanyon theme is pure CSS and a slightly modified version of the CSS is in the /static/css directory of the example repository. If you are following along, you should grab the static folder from the example repository and put it alongside the content folder you just created.

However looking at the static folder in master branch - there is only a favicon file, and no css files?

**Comment by dazinator** [comment]
Also when I got to the git commands:

```
# Create a new orphand branch (no commit history) named gh-pages
git checkout --orphan gh-pages

# Unstage all files
git rm --cached $(git ls-files)

# Grab one file from the master branch so we can make a commit
git checkout master README.md


```

`git rm --cached $(git ls-files)` didn't seem to work for me.
I used `git reset --hard` instead which appeared to work.

**Comment by sglyon** [comment]
I @dazinator that's correct. The css files are actually in the theme directory: https://github.com/sglyon/hugo_gh_blog/tree/master/themes/Lanyon/static/css
