### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by QIvan** [spencerlyon2/hugo_gh_blog#5]
Hi! Your [link](http://spencerlyon2.github.io/hugo_gh_blog) on demo is not working ( 

request: 
```bash
$ wget http://spencerlyon2.github.io/hugo_gh_blog
```

responce: 
```
--2017-01-10 01:27:41--  http://spencerlyon2.github.io/hugo_gh_blog
Resolving spencerlyon2.github.io (spencerlyon2.github.io)... 151.101.12.133
Connecting to spencerlyon2.github.io (spencerlyon2.github.io)|151.101.12.133|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-01-10 01:27:41 ERROR 404: Not Found.
```

I've found another link http://spencerlyon.com/hugo_gh_blog/ but here css is crashed.

**Comment by sglyon** [comment]
Thank you, I'll try to look at this tomorrow and find a fix

**Comment by sglyon** [comment]
http://spencerlyon.com/hugo_gh_blog/ is now fixed, thank you
